### ISSUE TITLE
Create a mega-sweep validator

### ISSUE THREAD

**Issue by douglasjacobsen** [UK-MAC/mega-stream#5]
It would be nice if there was some sort of correctness test to go along with mega-sweep, to help ensure that performance enhancements are implemented without adding bugs.

**Comment by tomdeakin** [comment]
I agree that it would be great to have some sort of validation on the solution. I've not yet managed to come up with a simple way to do this though. As the arrays all contain totally junk data (all variables are just set to a constant) there is no real way of analytically knowing what the correct solution should be without simply performing the computation. Due to the way the sweep progresses too, the solution will be different in each cell, so a simple approach of ensuring all the cells contain the same value doesn't work. The best I came up with was printing something like a population count (a big reduction) and keeping an eye on it as I made changes to the code. Do you have any ideas about how a more robust approach could be implemented?

**Comment by Pennycook** [comment]
There are two different kinds of validation I've seen in similar benchmarks, both of which would be useful:

1. Validating that the code gets the "right" answer
2. Validating that the optimized code gets the same answer as trusted code

What @tomdeakin has suggested so far sounds like 1 to me, and it would mainly be useful for checking whether the current implementation has bugs.  All @douglasjacobsen and I really need for optimization studies is 2; comparing the output values of every cell from a "gold" and optimized version of one sweep would be sufficient.

**Comment by tomdeakin** [comment]
The code already prints out an integrated metric labelled "Population", which comes from a reduction over all problem dimensions. This is the same approach that was used to validate `mega-stream`. It would be simple to print out one reduced value per energy group as well for extra checks. We could then run the "trusted" code to get the expected values ahead of any optimisation. Would this be an acceptable solution?

A solution in every cell would most simply require dumping out to a file the array which could then be compared against a similar "gold" file in a post-run checker script. It would be simple (and sensible) enough to add an option to produce an output file of the scalar flux array which would give `ng` values in each cell. I would definitely hesitate dumping out the angular flux with `ng * nang * nsweeps` values in each cell: for the default input in the 3D version a binary file would be ~35 GB.

Note that the scalar flux output would still be an integrated value based on all the sweeps in one `ntimes` iteration; 4 in 2D and 8 in 3D.

Which option would you prefer?

**Comment by douglasjacobsen** [comment]
@tomdeakin I think that your proposed solution of using population and then running a trusted version to get a baseline ahead of optimizations would be fine. The trouble is just getting the trusted version to a point that it is actually trusted. I think your gold file version could definitely help with that some.

Another idea I had about it would be to create a metric that is similar to population, but just add a 1 for each cell that does not have a 0.0 in it (as long as the math works out that resulting values should be positive definite). Then the metric should show that every location that is expected to be touched is in fact touched, and since the actual value in each location doesn't really matter this might be a bit more reliable than population (since population could alias missed locations since the actual value doesn't mean a whole lot).

**Comment by tomdeakin** [comment]
The code was already calculating and saving the population in each group in an array, but only printed out the total. I've updated both the 2D and 3D versions of `mega-sweep` to print out the population in all groups as well as the total.

I've also added a check which checks if any element of the `aflux` arrays is zero. If this is the case then it's likely that the sweep has missed touching a location. I tested this with the 3D code before your fix in #4 and the message was printed.

In general, the values might go negative because there is no mitigation for this in this code as it would add extra complexity not needed here for the performance studies. It may be possible that some values end up close to zero. Therefore checking for exactly zero will only catch cells which haven't been touched at all.
